DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS full_ordered;

CREATE TABLE orders (
  id SERIAL PRIMARY KEY,
  food_id INTEGER REFERENCES food_item(id),
  quantity SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);