DROP TABLE IF EXISTS order_contents CASCADE;
DROP TABLE IF EXISTS full_ordered;

CREATE TABLE order_contents (
  id SERIAL PRIMARY KEY NOT NULL,
  food_id INTEGER REFERENCES food_item(id),
  quantity SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  note TEXT
);
